# Generated by Django 5.1.4 on 2025-04-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StechApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='Project',
        ),
    ]
