# Generated by Django 5.1.4 on 2025-04-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StechApp', '0003_project_created_at_project_title_alter_project_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Client Name')),
                ('image', models.ImageField(upload_to='clients/', verbose_name='Photo')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
            ],
        ),
    ]
