# Generated by Django 5.1.4 on 2025-04-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StechApp', '0005_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('service', models.CharField(choices=[('consult', 'Consultant'), ('web_dev', 'Web Development'), ('app_dev', 'App Development'), ('seo', 'Digital Marketing / SEO'), ('maint', 'Website Maintenance'), ('redesign', 'Website Redesigning')], max_length=20)),
                ('message', models.TextField(max_length=1500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
