# Generated by Django 5.1.4 on 2025-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StechApp', '0006_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Your Email')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Rating (1 to 5)')),
                ('feedback', models.TextField(max_length=1500, verbose_name='Your Feedback')),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback_images/', verbose_name='Feedback Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Feedback Date')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
