# Generated by Django 5.1.4 on 2025-04-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StechApp', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('service_type', models.CharField(choices=[('Web Development', 'Web Development'), ('App Development', 'App Development'), ('SEO & Marketing', 'SEO & Marketing'), ('Desktop App', 'Desktop App'), ('Digital Marketing', 'Digital Marketing')], max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
