# Generated by Django 5.1.4 on 2025-04-29 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StechApp', '0010_alter_servicerequest_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='service_type',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service',
            field=models.CharField(choices=[('web', 'Web Development'), ('seo', 'SEO'), ('marketing', 'Digital Marketing'), ('design', 'UI/UX Design'), ('ecommerce', 'E-commerce Solutions'), ('app', 'App Development')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
