# Generated by Django 5.1.4 on 2025-04-29 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StechApp', '0011_remove_servicerequest_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='service',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
