# Generated by Django 5.1.4 on 2025-04-30 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StechApp', '0012_remove_servicerequest_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='service_type',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='app_type',
            field=models.CharField(choices=[('Basic', 'Basic App'), ('Business', 'Business App'), ('Advanced', 'Advanced App')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='company_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Small', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='department',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('App Development', 'App Development'), ('Digital Marketing', 'Digital Marketing'), ('Web Maintenance', 'Web Maintenance'), ('Web Redesigning', 'Web Redesigning'), ('SEO Marketing', 'SEO Marketing')], default='Small', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='industry',
            field=models.CharField(choices=[('IT', 'IT'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Retail Ecommerce', 'Retail Ecommerce'), ('Manufacturing', 'Manufacturing'), ('Media & Communication', 'Media & Communication'), ('NEOS', 'NEOS')], default='IT', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='page_range',
            field=models.CharField(choices=[('1-3', '1-3 Pages'), ('1-5', '1-5 Pages'), ('1-7', '1-7 Pages'), ('7+', 'Up to 14 Pages')], default='1-3 ranges', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='product_services',
            field=models.CharField(default='website', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='website_type',
            field=models.CharField(choices=[('Static', 'Static Website'), ('Dynamic', 'Dynamic Website'), ('Ecommerce', 'Ecommerce Website')], default='No message', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='message',
            field=models.TextField(max_length=1500),
        ),
    ]
