# Generated by Django 5.1.4 on 2025-04-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StechApp', '0013_remove_servicerequest_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='desktop_package',
            field=models.CharField(choices=[('Basic', 'Basic Desktop App'), ('Business', 'Business Desktop App'), ('Advanced', 'Advanced Desktop Solution'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='digital_package',
            field=models.CharField(choices=[('Starter', 'Starter Package'), ('Growth', 'Growth Package'), ('Premium', 'Premium Package'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='app_type',
            field=models.CharField(choices=[('Basic', 'Basic App'), ('Business', 'Business App'), ('Advanced', 'Advanced App'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='website_type',
            field=models.CharField(choices=[('Static', 'Static Website'), ('Dynamic', 'Dynamic Website'), ('Ecommerce', 'Ecommerce Website'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
