# Generated by Django 5.1.4 on 2025-04-30 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StechApp', '0015_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='education',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='role',
            field=models.CharField(default='Unspecified', max_length=50),
            preserve_default=False,
        ),
    ]
