# Generated by Django 5.1.4 on 2025-04-30 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StechApp', '0016_remove_jobapplication_applied_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
